// constant files

export const ADD_ABOUTIMAGE_REQUEST = "ADD_ABOUTIMAGE_REQUEST";
export const ADD_ABOUTIMAGE_SUCCESS = "ADD_ABOUTIMAGE_SUCCESS";
export const ADD_ABOUTIMAGE_FAIL = "ADD_ABOUTIMAGE_FAIL";

export const UPDATE_ABOUTIMAGE_REQUEST = "UPDATE_ABOUTIMAGE_REQUEST";
export const UPDATE_ABOUTIMAGE_SUCCESS = "UPDATE_ABOUTIMAGE_SUCCESS";
export const UPDATE_ABOUTIMAGE_FAIL = "UPDATE_ABOUTIMAGE_FAIL";

export const DELETE_ABOUTIMAGE_REQUEST = "DELETE_ABOUTIMAGE_REQUEST";
export const DELETE_ABOUTIMAGE_SUCCESS = "DELETE_ABOUTIMAGE_SUCCESS";
export const DELETE_ABOUTIMAGE_FAIL = "DELETE_ABOUTIMAGE_FAIL";

export const GETALL_ABOUTIMAGE_REQUEST = "GETALL_ABOUTIMAGE_REQUEST";
export const GETALL_ABOUTIMAGE_SUCCESS = "GETALL_ABOUTIMAGE_SUCCESS";
export const GETALL_ABOUTIMAGE_FAIL = "GETALL_ABOUTIMAGE_FAIL";

export const GETDETAIL_ABOUTIMAGE_REQUEST = "GETDETAIL_ABOUTIMAGE_REQUEST";
export const GETDETAIL_ABOUTIMAGE_SUCCESS = "GETDETAIL_ABOUTIMAGE_SUCCESS";
export const GETDETAIL_ABOUTIMAGE_FAIL = "GETDETAIL_ABOUTIMAGE_FAIL";

export const ABOUTIMAGE_CHANGE_STATUS_REQUEST =
  "ABOUTIMAGE_CHANGE_STATUS_REQUEST";
export const ABOUTIMAGE_CHANGE_STATUS_SUCCESS =
  "ABOUTIMAGE_CHANGE_STATUS_SUCCESS";
export const ABOUTIMAGE_CHANGE_STATUS_FAIL = "ABOUTIMAGE_CHANGE_STATUS_FAIL";
