// constant files

export const ADD_ABOUT_REQUEST = "ADD_ABOUT_REQUEST";
export const ADD_ABOUT_SUCCESS = "ADD_ABOUT_SUCCESS";
export const ADD_ABOUT_FAIL = "ADD_ABOUT_FAIL";

export const UPDATE_ABOUT_REQUEST = "UPDATE_ABOUT_REQUEST";
export const UPDATE_ABOUT_SUCCESS = "UPDATE_ABOUT_SUCCESS";
export const UPDATE_ABOUT_FAIL = "UPDATE_ABOUT_FAIL";

export const DELETE_ABOUT_REQUEST = "DELETE_ABOUT_REQUEST";
export const DELETE_ABOUT_SUCCESS = "DELETE_ABOUT_SUCCESS";
export const DELETE_ABOUT_FAIL = "DELETE_ABOUT_FAIL";

export const GETALL_ABOUT_REQUEST = "GETALL_ABOUT_REQUEST";
export const GETALL_ABOUT_SUCCESS = "GETALL_ABOUT_SUCCESS";
export const GETALL_ABOUT_FAIL = "GETALL_ABOUT_FAIL";

export const GETDETAIL_ABOUT_REQUEST = "GETDETAIL_ABOUT_REQUEST";
export const GETDETAIL_ABOUT_SUCCESS = "GETDETAIL_ABOUT_SUCCESS";
export const GETDETAIL_ABOUT_FAIL = "GETDETAIL_ABOUT_FAIL";

export const ABOUT_CHANGE_STATUS_REQUEST =
  "ABOUT_CHANGE_STATUS_REQUEST";
export const ABOUT_CHANGE_STATUS_SUCCESS =
  "ABOUT_CHANGE_STATUS_SUCCESS";
export const ABOUT_CHANGE_STATUS_FAIL = "ABOUT_CHANGE_STATUS_FAIL";
