// constant files

export const ADD_BANNER_PRODUCT_REQUEST = "ADD_BANNER_PRODUCT_REQUEST";
export const ADD_BANNER_PRODUCT_SUCCESS = "ADD_BANNER_PRODUCT_SUCCESS";
export const ADD_BANNER_PRODUCT_FAIL = "ADD_BANNER_PRODUCT_FAIL";

export const UPDATE_BANNER_PRODUCT_REQUEST = "UPDATE_BANNER_PRODUCT_REQUEST";
export const UPDATE_BANNER_PRODUCT_SUCCESS = "UPDATE_BANNER_PRODUCT_SUCCESS";
export const UPDATE_BANNER_PRODUCT_FAIL = "UPDATE_BANNER_PRODUCT_FAIL";

export const DELETE_BANNER_PRODUCT_REQUEST = "DELETE_BANNER_PRODUCT_REQUEST";
export const DELETE_BANNER_PRODUCT_SUCCESS = "DELETE_BANNER_PRODUCT_SUCCESS";
export const DELETE_BANNER_PRODUCT_FAIL = "DELETE_BANNER_PRODUCT_FAIL";

export const GET_ALL_BANNER_PRODUCT_REQUEST = "GET_ALL_BANNER_PRODUCT_REQUEST";
export const GET_ALL_BANNER_PRODUCT_SUCCESS = "GET_ALL_BANNER_PRODUCT_SUCCESS";
export const GET_ALL_BANNER_PRODUCT_FAIL = "GET_ALL_BANNER_PRODUCT_FAIL";

export const GET_SINGLE_BANNER_PRODUCT_REQUEST =
  "GET_SINGLE_BANNER_PRODUCT_REQUEST";
export const GET_SINGLE_BANNER_PRODUCT_SUCCESS =
  "GET_SINGLE_BANNER_PRODUCT_SUCCESS";
export const GET_SINGLE_BANNER_PRODUCT_FAIL = "GET_SINGLE_BANNER_PRODUCT_FAIL";

export const BANNER_PRODUCT_CHANGE_STATUS_REQUEST =
  "BANNER_PRODUCT_CHANGE_STATUS_REQUEST";
export const BANNER_PRODUCT_CHANGE_STATUS_SUCCESS =
  "BANNER_PRODUCT_CHANGE_STATUS_SUCCESS";
export const BANNER_PRODUCT_CHANGE_STATUS_FAIL =
  "BANNER_PRODUCT_CHANGE_STATUS_FAIL";
