// constant files

export const ADD_BANNER_REQUEST = "ADD_BANNER_REQUEST";
export const ADD_BANNER_SUCCESS = "ADD_BANNER_SUCCESS";
export const ADD_BANNER_FAIL = "ADD_BANNER_FAIL";

export const UPDATE_BANNER_REQUEST = "UPDATE_BANNER_REQUEST";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAIL = "UPDATE_BANNER_FAIL";

export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";

export const GET_ALL_BANNER_REQUEST = "GET_ALL_BANNER_REQUEST";
export const GET_ALL_BANNER_SUCCESS = "GET_ALL_BANNER_SUCCESS";
export const GET_ALL_BANNER_FAIL = "GET_ALL_BANNER_FAIL";

export const GET_SINGLE_BANNER_REQUEST = "GET_SINGLE_BANNER_REQUEST";
export const GET_SINGLE_BANNER_SUCCESS = "GET_SINGLE_BANNER_SUCCESS";
export const GET_SINGLE_BANNER_FAIL = "GET_SINGLE_BANNER_FAIL";

export const BANNER_CHANGE_STATUS_REQUEST = "BANNER_CHANGE_STATUS_REQUEST";
export const BANNER_CHANGE_STATUS_SUCCESS = "BANNER_CHANGE_STATUS_SUCCESS";
export const BANNER_CHANGE_STATUS_FAIL = "BANNER_CHANGE_STATUS_FAIL";
