// constant files

export const ADD_BEST_USES_REQUEST = "ADD_BEST_USES_REQUEST";
export const ADD_BEST_USES_SUCCESS = "ADD_BEST_USES_SUCCESS";
export const ADD_BEST_USES_FAIL = "ADD_BEST_USES_FAIL";

export const UPDATE_BEST_USES_REQUEST = "UPDATE_BEST_USES_REQUEST";
export const UPDATE_BEST_USES_SUCCESS = "UPDATE_BEST_USES_SUCCESS";
export const UPDATE_BEST_USES_FAIL = "UPDATE_BEST_USES_FAIL";

export const DELETE_BEST_USES_REQUEST = "DELETE_BEST_USES_REQUEST";
export const DELETE_BEST_USES_SUCCESS = "DELETE_BEST_USES_SUCCESS";
export const DELETE_BEST_USES_FAIL = "DELETE_BEST_USES_FAIL";

export const GET_ALL_BEST_USES_REQUEST = "GET_ALL_BEST_USES_REQUEST";
export const GET_ALL_BEST_USES_SUCCESS = "GET_ALL_BEST_USES_SUCCESS";
export const GET_ALL_BEST_USES_FAIL = "GET_ALL_BEST_USES_FAIL";

export const GET_SINGLE_BEST_USES_REQUEST = "GET_SINGLE_BEST_USES_REQUEST";
export const GET_SINGLE_BEST_USES_SUCCESS = "GET_SINGLE_BEST_USES_SUCCESS";
export const GET_SINGLE_BEST_USES_FAIL = "GET_SINGLE_BEST_USES_FAIL";

export const BEST_USES_CHANGE_STATUS_REQUEST =
  "BEST_USES_CHANGE_STATUS_REQUEST";
export const BEST_USES_CHANGE_STATUS_SUCCESS =
  "BEST_USES_CHANGE_STATUS_SUCCESS";
export const BEST_USES_CHANGE_STATUS_FAIL = "BEST_USES_CHANGE_STATUS_FAIL";
