// constant files

export const ADD_BLOG_REQUEST = "ADD_BLOG_REQUEST";
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS";
export const ADD_BLOG_FAIL = "ADD_BLOG_FAIL";

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";

export const GETALL_BLOG_REQUEST = "GETALL_BLOG_REQUEST";
export const GETALL_BLOG_SUCCESS = "GETALL_BLOG_SUCCESS";
export const GETALL_BLOG_FAIL = "GETALL_BLOG_FAIL";

export const GETDETAIL_BLOG_REQUEST = "GETDETAIL_BLOG_REQUEST";
export const GETDETAIL_BLOG_SUCCESS = "GETDETAIL_BLOG_SUCCESS";
export const GETDETAIL_BLOG_FAIL = "GETDETAIL_BLOG_FAIL";

export const BLOG_CHANGE_STATUS_REQUEST = "BLOG_CHANGE_STATUS_REQUEST";
export const BLOG_CHANGE_STATUS_SUCCESS = "BLOG_CHANGE_STATUS_SUCCESS";
export const BLOG_CHANGE_STATUS_FAIL = "BLOG_CHANGE_STATUS_FAIL";
