// constant files

export const ADD_BOOKAPPOINTMENT_REQUEST = "ADD_BOOKAPPOINTMENT_REQUEST";
export const ADD_BOOKAPPOINTMENT_SUCCESS = "ADD_BOOKAPPOINTMENT_SUCCESS";
export const ADD_BOOKAPPOINTMENT_FAIL = "ADD_BOOKAPPOINTMENT_FAIL";

export const UPDATE_BOOKAPPOINTMENT_REQUEST = "UPDATE_BOOKAPPOINTMENT_REQUEST";
export const UPDATE_BOOKAPPOINTMENT_SUCCESS = "UPDATE_BOOKAPPOINTMENT_SUCCESS";
export const UPDATE_BOOKAPPOINTMENT_FAIL = "UPDATE_BOOKAPPOINTMENT_FAIL";

export const DELETE_BOOKAPPOINTMENT_REQUEST = "DELETE_BOOKAPPOINTMENT_REQUEST";
export const DELETE_BOOKAPPOINTMENT_SUCCESS = "DELETE_BOOKAPPOINTMENT_SUCCESS";
export const DELETE_BOOKAPPOINTMENT_FAIL = "DELETE_BOOKAPPOINTMENT_FAIL";

export const GETALL_BOOKAPPOINTMENT_REQUEST = "GETALL_BOOKAPPOINTMENT_REQUEST";
export const GETALL_BOOKAPPOINTMENT_SUCCESS = "GETALL_BOOKAPPOINTMENT_SUCCESS";
export const GETALL_BOOKAPPOINTMENT_FAIL = "GETALL_BOOKAPPOINTMENT_FAIL";

export const GETDETAIL_BOOKAPPOINTMENT_REQUEST =
  "GETDETAIL_BOOKAPPOINTMENT_REQUEST";
export const GETDETAIL_BOOKAPPOINTMENT_SUCCESS =
  "GETDETAIL_BOOKAPPOINTMENT_SUCCESS";
export const GETDETAIL_BOOKAPPOINTMENT_FAIL = "GETDETAIL_BOOKAPPOINTMENT_FAIL";

export const BOOKAPPOINTMENT_CHANGE_STATUS_REQUEST =
  "BOOKAPPOINTMENT_CHANGE_STATUS_REQUEST";
export const BOOKAPPOINTMENT_CHANGE_STATUS_SUCCESS =
  "BOOKAPPOINTMENT_CHANGE_STATUS_SUCCESS";
export const BOOKAPPOINTMENT_CHANGE_STATUS_FAIL =
  "BOOKAPPOINTMENT_CHANGE_STATUS_FAIL";
