// constant files

export const ADD_CAREER_REQUEST = "ADD_CAREER_REQUEST";
export const ADD_CAREER_SUCCESS = "ADD_CAREER_SUCCESS";
export const ADD_CAREER_FAIL = "ADD_CAREER_FAIL";

export const UPDATE_CAREER_REQUEST = "UPDATE_CAREER_REQUEST";
export const UPDATE_CAREER_SUCCESS = "UPDATE_CAREER_SUCCESS";
export const UPDATE_CAREER_FAIL = "UPDATE_CAREER_FAIL";

export const DELETE_CAREER_REQUEST = "DELETE_CAREER_REQUEST";
export const DELETE_CAREER_SUCCESS = "DELETE_CAREER_SUCCESS";
export const DELETE_CAREER_FAIL = "DELETE_CAREER_FAIL";

export const GETALL_CAREER_REQUEST = "GETALL_CAREER_REQUEST";
export const GETALL_CAREER_SUCCESS = "GETALL_CAREER_SUCCESS";
export const GETALL_CAREER_FAIL = "GETALL_CAREER_FAIL";

export const GETDETAIL_CAREER_REQUEST = "GETDETAIL_CAREER_REQUEST";
export const GETDETAIL_CAREER_SUCCESS = "GETDETAIL_CAREER_SUCCESS";
export const GETDETAIL_CAREER_FAIL = "GETDETAIL_CAREER_FAIL";

export const CAREER_CHANGE_STATUS_REQUEST = "CAREER_CHANGE_STATUS_REQUEST";
export const CAREER_CHANGE_STATUS_SUCCESS = "CAREER_CHANGE_STATUS_SUCCESS";
export const CAREER_CHANGE_STATUS_FAIL = "CAREER_CHANGE_STATUS_FAIL";
