// constant files

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";

export const GETALL_CATEGORY_REQUEST = "GETALL_CATEGORY_REQUEST";
export const GETALL_CATEGORY_SUCCESS = "GETALL_CATEGORY_SUCCESS";
export const GETALL_CATEGORY_FAIL = "GETALL_CATEGORY_FAIL";

export const GETDETAIL_CATEGORY_REQUEST = "GETDETAIL_CATEGORY_REQUEST";
export const GETDETAIL_CATEGORY_SUCCESS = "GETDETAIL_CATEGORY_SUCCESS";
export const GETDETAIL_CATEGORY_FAIL = "GETDETAIL_CATEGORY_FAIL";

export const CATEGORY_CHANGE_STATUS_REQUEST = "CATEGORY_CHANGE_STATUS_REQUEST";
export const CATEGORY_CHANGE_STATUS_SUCCESS = "CATEGORY_CHANGE_STATUS_SUCCESS";
export const CATEGORY_CHANGE_STATUS_FAIL = "CATEGORY_CHANGE_STATUS_FAIL";
