// constant files

export const ADD_CATEGORYCONTENT_REQUEST = "ADD_CATEGORYCONTENT_REQUEST";
export const ADD_CATEGORYCONTENT_SUCCESS = "ADD_CATEGORYCONTENT_SUCCESS";
export const ADD_CATEGORYCONTENT_FAIL = "ADD_CATEGORYCONTENT_FAIL";

export const UPDATE_CATEGORYCONTENT_REQUEST = "UPDATE_CATEGORYCONTENT_REQUEST";
export const UPDATE_CATEGORYCONTENT_SUCCESS = "UPDATE_CATEGORYCONTENT_SUCCESS";
export const UPDATE_CATEGORYCONTENT_FAIL = "UPDATE_CATEGORYCONTENT_FAIL";

export const DELETE_CATEGORYCONTENT_REQUEST = "DELETE_CATEGORYCONTENT_REQUEST";
export const DELETE_CATEGORYCONTENT_SUCCESS = "DELETE_CATEGORYCONTENT_SUCCESS";
export const DELETE_CATEGORYCONTENT_FAIL = "DELETE_CATEGORYCONTENT_FAIL";

export const GETALL_CATEGORYCONTENT_REQUEST = "GETALL_CATEGORYCONTENT_REQUEST";
export const GETALL_CATEGORYCONTENT_SUCCESS = "GETALL_CATEGORYCONTENT_SUCCESS";
export const GETALL_CATEGORYCONTENT_FAIL = "GETALL_CATEGORYCONTENT_FAIL";

export const GETDETAIL_CATEGORYCONTENT_REQUEST = "GETDETAIL_CATEGORYCONTENT_REQUEST";
export const GETDETAIL_CATEGORYCONTENT_SUCCESS = "GETDETAIL_CATEGORYCONTENT_SUCCESS";
export const GETDETAIL_CATEGORYCONTENT_FAIL = "GETDETAIL_CATEGORYCONTENT_FAIL";

export const CATEGORYCONTENT_CHANGE_STATUS_REQUEST = "CATEGORYCONTENT_CHANGE_STATUS_REQUEST";
export const CATEGORYCONTENT_CHANGE_STATUS_SUCCESS = "CATEGORYCONTENT_CHANGE_STATUS_SUCCESS";
export const CATEGORYCONTENT_CHANGE_STATUS_FAIL = "CATEGORYCONTENT_CHANGE_STATUS_FAIL";
