// constant files

export const ADD_CONS_REQUEST = "ADD_CONS_REQUEST";
export const ADD_CONS_SUCCESS = "ADD_CONS_SUCCESS";
export const ADD_CONS_FAIL = "ADD_CONS_FAIL";

export const UPDATE_CONS_REQUEST = "UPDATE_CONS_REQUEST";
export const UPDATE_CONS_SUCCESS = "UPDATE_CONS_SUCCESS";
export const UPDATE_CONS_FAIL = "UPDATE_CONS_FAIL";

export const DELETE_CONS_REQUEST = "DELETE_CONS_REQUEST";
export const DELETE_CONS_SUCCESS = "DELETE_CONS_SUCCESS";
export const DELETE_CONS_FAIL = "DELETE_CONS_FAIL";

export const GET_ALL_CONS_REQUEST = "GET_ALL_CONS_REQUEST";
export const GET_ALL_CONS_SUCCESS = "GET_ALL_CONS_SUCCESS";
export const GET_ALL_CONS_FAIL = "GET_ALL_CONS_FAIL";

export const GET_SINGLE_CONS_REQUEST = "GET_SINGLE_CONS_REQUEST";
export const GET_SINGLE_CONS_SUCCESS = "GET_SINGLE_CONS_SUCCESS";
export const GET_SINGLE_CONS_FAIL = "GET_SINGLE_CONS_FAIL";

export const CONS_CHANGE_STATUS_REQUEST = "CONS_CHANGE_STATUS_REQUEST";
export const CONS_CHANGE_STATUS_SUCCESS = "CONS_CHANGE_STATUS_SUCCESS";
export const CONS_CHANGE_STATUS_FAIL = "CONS_CHANGE_STATUS_FAIL";
