// constant files

export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";

export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAIL = "UPDATE_CONTACT_FAIL";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

export const GET_ALL_CONTACT_REQUEST = "GET_ALL_CONTACT_REQUEST";
export const GET_ALL_CONTACT_SUCCESS = "GET_ALL_CONTACT_SUCCESS";
export const GET_ALL_CONTACT_FAIL = "GET_ALL_CONTACT_FAIL";

export const GET_SINGLE_CONTACT_REQUEST = "GET_SINGLE_CONTACT_REQUEST";
export const GET_SINGLE_CONTACT_SUCCESS = "GET_SINGLE_CONTACT_SUCCESS";
export const GET_SINGLE_CONTACT_FAIL = "GET_SINGLE_CONTACT_FAIL";

export const CONTACT_CHANGE_STATUS_REQUEST = "CONTACT_CHANGE_STATUS_REQUEST";
export const CONTACT_CHANGE_STATUS_SUCCESS = "CONTACT_CHANGE_STATUS_SUCCESS";
export const CONTACT_CHANGE_STATUS_FAIL = "CONTACT_CHANGE_STATUS_FAIL";
