// constant files

export const ADD_COVID_REQUEST = "ADD_COVID_REQUEST";
export const ADD_COVID_SUCCESS = "ADD_COVID_SUCCESS";
export const ADD_COVID_FAIL = "ADD_COVID_FAIL";

export const UPDATE_COVID_REQUEST = "UPDATE_COVID_REQUEST";
export const UPDATE_COVID_SUCCESS = "UPDATE_COVID_SUCCESS";
export const UPDATE_COVID_FAIL = "UPDATE_COVID_FAIL";

export const DELETE_COVID_REQUEST = "DELETE_COVID_REQUEST";
export const DELETE_COVID_SUCCESS = "DELETE_COVID_SUCCESS";
export const DELETE_COVID_FAIL = "DELETE_COVID_FAIL";

export const GET_ALL_COVID_REQUEST = "GET_ALL_COVID_REQUEST";
export const GET_ALL_COVID_SUCCESS = "GET_ALL_COVID_SUCCESS";
export const GET_ALL_COVID_FAIL = "GET_ALL_COVID_FAIL";

export const GET_SINGLE_COVID_REQUEST = "GET_SINGLE_COVID_REQUEST";
export const GET_SINGLE_COVID_SUCCESS = "GET_SINGLE_COVID_SUCCESS";
export const GET_SINGLE_COVID_FAIL = "GET_SINGLE_COVID_FAIL";

export const COVID_CHANGE_STATUS_REQUEST = "COVID_CHANGE_STATUS_REQUEST";
export const COVID_CHANGE_STATUS_SUCCESS = "COVID_CHANGE_STATUS_SUCCESS";
export const COVID_CHANGE_STATUS_FAIL = "COVID_CHANGE_STATUS_FAIL";
