// constant files

export const ADD_DASHBOARDCONTENT_REQUEST = "ADD_DASHBOARDCONTENT_REQUEST";
export const ADD_DASHBOARDCONTENT_SUCCESS = "ADD_DASHBOARDCONTENT_SUCCESS";
export const ADD_DASHBOARDCONTENT_FAIL = "ADD_DASHBOARDCONTENT_FAIL";

export const UPDATE_DASHBOARDCONTENT_REQUEST =
  "UPDATE_DASHBOARDCONTENT_REQUEST";
export const UPDATE_DASHBOARDCONTENT_SUCCESS =
  "UPDATE_DASHBOARDCONTENT_SUCCESS";
export const UPDATE_DASHBOARDCONTENT_FAIL = "UPDATE_DASHBOARDCONTENT_FAIL";

export const DELETE_DASHBOARDCONTENT_REQUEST =
  "DELETE_DASHBOARDCONTENT_REQUEST";
export const DELETE_DASHBOARDCONTENT_SUCCESS =
  "DELETE_DASHBOARDCONTENT_SUCCESS";
export const DELETE_DASHBOARDCONTENT_FAIL = "DELETE_DASHBOARDCONTENT_FAIL";

export const GETALL_DASHBOARDCONTENT_REQUEST =
  "GETALL_DASHBOARDCONTENT_REQUEST";
export const GETALL_DASHBOARDCONTENT_SUCCESS =
  "GETALL_DASHBOARDCONTENT_SUCCESS";
export const GETALL_DASHBOARDCONTENT_FAIL = "GETALL_DASHBOARDCONTENT_FAIL";

export const GETDETAIL_DASHBOARDCONTENT_REQUEST =
  "GETDETAIL_DASHBOARDCONTENT_REQUEST";
export const GETDETAIL_DASHBOARDCONTENT_SUCCESS =
  "GETDETAIL_DASHBOARDCONTENT_SUCCESS";
export const GETDETAIL_DASHBOARDCONTENT_FAIL =
  "GETDETAIL_DASHBOARDCONTENT_FAIL";

export const DASHBOARDCONTENT_CHANGE_STATUS_REQUEST =
  "DASHBOARDCONTENT_CHANGE_STATUS_REQUEST";
export const DASHBOARDCONTENT_CHANGE_STATUS_SUCCESS =
  "DASHBOARDCONTENT_CHANGE_STATUS_SUCCESS";
export const DASHBOARDCONTENT_CHANGE_STATUS_FAIL =
  "DASHBOARDCONTENT_CHANGE_STATUS_FAIL";
