// constant files

export const ADD_DASHBOARDBANNER_REQUEST = "ADD_DASHBOARDBANNER_REQUEST";
export const ADD_DASHBOARDBANNER_SUCCESS = "ADD_DASHBOARDBANNER_SUCCESS";
export const ADD_DASHBOARDBANNER_FAIL = "ADD_DASHBOARDBANNER_FAIL";

export const UPDATE_DASHBOARDBANNER_REQUEST = "UPDATE_DASHBOARDBANNER_REQUEST";
export const UPDATE_DASHBOARDBANNER_SUCCESS = "UPDATE_DASHBOARDBANNER_SUCCESS";
export const UPDATE_DASHBOARDBANNER_FAIL = "UPDATE_DASHBOARDBANNER_FAIL";

export const DELETE_DASHBOARDBANNER_REQUEST = "DELETE_DASHBOARDBANNER_REQUEST";
export const DELETE_DASHBOARDBANNER_SUCCESS = "DELETE_DASHBOARDBANNER_SUCCESS";
export const DELETE_DASHBOARDBANNER_FAIL = "DELETE_DASHBOARDBANNER_FAIL";

export const GETALL_DASHBOARDBANNER_REQUEST = "GETALL_DASHBOARDBANNER_REQUEST";
export const GETALL_DASHBOARDBANNER_SUCCESS = "GETALL_DASHBOARDBANNER_SUCCESS";
export const GETALL_DASHBOARDBANNER_FAIL = "GETALL_DASHBOARDBANNER_FAIL";

export const GETDETAIL_DASHBOARDBANNER_REQUEST =
  "GETDETAIL_DASHBOARDBANNER_REQUEST";
export const GETDETAIL_DASHBOARDBANNER_SUCCESS =
  "GETDETAIL_DASHBOARDBANNER_SUCCESS";
export const GETDETAIL_DASHBOARDBANNER_FAIL = "GETDETAIL_DASHBOARDBANNER_FAIL";

export const DASHBOARDBANNER_CHANGE_STATUS_REQUEST =
  "DASHBOARDBANNER_CHANGE_STATUS_REQUEST";
export const DASHBOARDBANNER_CHANGE_STATUS_SUCCESS =
  "DASHBOARDBANNER_CHANGE_STATUS_SUCCESS";
export const DASHBOARDBANNER_CHANGE_STATUS_FAIL =
  "DASHBOARDBANNER_CHANGE_STATUS_FAIL";
