// constant files

export const ADD_DATASECURITY_REQUEST = "ADD_DATASECURITY_REQUEST";
export const ADD_DATASECURITY_SUCCESS = "ADD_DATASECURITY_SUCCESS";
export const ADD_DATASECURITY_FAIL = "ADD_DATASECURITY_FAIL";

export const UPDATE_DATASECURITY_REQUEST = "UPDATE_DATASECURITY_REQUEST";
export const UPDATE_DATASECURITY_SUCCESS = "UPDATE_DATASECURITY_SUCCESS";
export const UPDATE_DATASECURITY_FAIL = "UPDATE_DATASECURITY_FAIL";

export const DELETE_DATASECURITY_REQUEST = "DELETE_DATASECURITY_REQUEST";
export const DELETE_DATASECURITY_SUCCESS = "DELETE_DATASECURITY_SUCCESS";
export const DELETE_DATASECURITY_FAIL = "DELETE_DATASECURITY_FAIL";

export const GETALL_DATASECURITY_REQUEST = "GETALL_DATASECURITY_REQUEST";
export const GETALL_DATASECURITY_SUCCESS = "GETALL_DATASECURITY_SUCCESS";
export const GETALL_DATASECURITY_FAIL = "GETALL_DATASECURITY_FAIL";

export const GETDETAIL_DATASECURITY_REQUEST = "GETDETAIL_DATASECURITY_REQUEST";
export const GETDETAIL_DATASECURITY_SUCCESS = "GETDETAIL_DATASECURITY_SUCCESS";
export const GETDETAIL_DATASECURITY_FAIL = "GETDETAIL_DATASECURITY_FAIL";

export const DATASECURITY_CHANGE_STATUS_REQUEST =
  "DATASECURITY_CHANGE_STATUS_REQUEST";
export const DATASECURITY_CHANGE_STATUS_SUCCESS =
  "DATASECURITY_CHANGE_STATUS_SUCCESS";
export const DATASECURITY_CHANGE_STATUS_FAIL = "DATASECURITY_CHANGE_STATUS_FAIL";
