// constant files

export const ADD_EMAIL_REQUEST = "ADD_EMAIL_REQUEST";
export const ADD_EMAIL_SUCCESS = "ADD_EMAIL_SUCCESS";
export const ADD_EMAIL_FAIL = "ADD_EMAIL_FAIL";

export const UPDATE_EMAIL_REQUEST = "UPDATE_EMAIL_REQUEST";
export const UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS";
export const UPDATE_EMAIL_FAIL = "UPDATE_EMAIL_FAIL";

export const DELETE_EMAIL_REQUEST = "DELETE_EMAIL_REQUEST";
export const DELETE_EMAIL_SUCCESS = "DELETE_EMAIL_SUCCESS";
export const DELETE_EMAIL_FAIL = "DELETE_EMAIL_FAIL";

export const GET_ALL_EMAIL_REQUEST = "GET_ALL_EMAIL_REQUEST";
export const GET_ALL_EMAIL_SUCCESS = "GET_ALL_EMAIL_SUCCESS";
export const GET_ALL_EMAIL_FAIL = "GET_ALL_EMAIL_FAIL";

export const GET_SINGLE_EMAIL_REQUEST = "GET_SINGLE_EMAIL_REQUEST";
export const GET_SINGLE_EMAIL_SUCCESS = "GET_SINGLE_EMAIL_SUCCESS";
export const GET_SINGLE_EMAIL_FAIL = "GET_SINGLE_EMAIL_FAIL";

export const EMAIL_CHANGE_STATUS_REQUEST = "EMAIL_CHANGE_STATUS_REQUEST";
export const EMAIL_CHANGE_STATUS_SUCCESS = "EMAIL_CHANGE_STATUS_SUCCESS";
export const EMAIL_CHANGE_STATUS_FAIL = "EMAIL_CHANGE_STATUS_FAIL";
