// constant files

export const ADD_ENQUIRY_REQUEST = "ADD_ENQUIRY_REQUEST";
export const ADD_ENQUIRY_SUCCESS = "ADD_ENQUIRY_SUCCESS";
export const ADD_ENQUIRY_FAIL = "ADD_ENQUIRY_FAIL";

export const UPDATE_ENQUIRY_REQUEST = "UPDATE_ENQUIRY_REQUEST";
export const UPDATE_ENQUIRY_SUCCESS = "UPDATE_ENQUIRY_SUCCESS";
export const UPDATE_ENQUIRY_FAIL = "UPDATE_ENQUIRY_FAIL";

export const DELETE_ENQUIRY_REQUEST = "DELETE_ENQUIRY_REQUEST";
export const DELETE_ENQUIRY_SUCCESS = "DELETE_ENQUIRY_SUCCESS";
export const DELETE_ENQUIRY_FAIL = "DELETE_ENQUIRY_FAIL";

export const GET_ALL_ENQUIRY_REQUEST = "GET_ALL_ENQUIRY_REQUEST";
export const GET_ALL_ENQUIRY_SUCCESS = "GET_ALL_ENQUIRY_SUCCESS";
export const GET_ALL_ENQUIRY_FAIL = "GET_ALL_ENQUIRY_FAIL";

export const GET_SINGLE_ENQUIRY_REQUEST = "GET_SINGLE_ENQUIRY_REQUEST";
export const GET_SINGLE_ENQUIRY_SUCCESS = "GET_SINGLE_ENQUIRY_SUCCESS";
export const GET_SINGLE_ENQUIRY_FAIL = "GET_SINGLE_ENQUIRY_FAIL";

// export const ENQUIRY_CHANGE_STATUS_REQUEST = "ENQUIRY_CHANGE_STATUS_REQUEST";
// export const ENQUIRY_CHANGE_STATUS_SUCCESS = "ENQUIRY_CHANGE_STATUS_SUCCESS";
// export const ENQUIRY_CHANGE_STATUS_FAIL = "ENQUIRY_CHANGE_STATUS_FAIL";
