// constant files

export const ADD_FAQ_REQUEST = "ADD_FAQ_REQUEST";
export const ADD_FAQ_SUCCESS = "ADD_FAQ_SUCCESS";
export const ADD_FAQ_FAIL = "ADD_FAQ_FAIL";

export const UPDATE_FAQ_REQUEST = "UPDATE_FAQ_REQUEST";
export const UPDATE_FAQ_SUCCESS = "UPDATE_FAQ_SUCCESS";
export const UPDATE_FAQ_FAIL = "UPDATE_FAQ_FAIL";

export const DELETE_FAQ_REQUEST = "DELETE_FAQ_REQUEST";
export const DELETE_FAQ_SUCCESS = "DELETE_FAQ_SUCCESS";
export const DELETE_FAQ_FAIL = "DELETE_FAQ_FAIL";

export const GETALL_FAQ_REQUEST = "GETALL_FAQ_REQUEST";
export const GETALL_FAQ_SUCCESS = "GETALL_FAQ_SUCCESS";
export const GETALL_FAQ_FAIL = "GETALL_FAQ_FAIL";

export const GETDETAIL_FAQ_REQUEST = "GETDETAIL_FAQ_REQUEST";
export const GETDETAIL_FAQ_SUCCESS = "GETDETAIL_FAQ_SUCCESS";
export const GETDETAIL_FAQ_FAIL = "GETDETAIL_FAQ_FAIL";

export const FAQ_CHANGE_STATUS_REQUEST = "FAQ_CHANGE_STATUS_REQUEST";
export const FAQ_CHANGE_STATUS_SUCCESS = "FAQ_CHANGE_STATUS_SUCCESS";
export const FAQ_CHANGE_STATUS_FAIL = "FAQ_CHANGE_STATUS_FAIL";
