// constant files

export const ADD_FIXBANNER_REQUEST = "ADD_FIXBANNER_REQUEST";
export const ADD_FIXBANNER_SUCCESS = "ADD_FIXBANNER_SUCCESS";
export const ADD_FIXBANNER_FAIL = "ADD_FIXBANNER_FAIL";

export const UPDATE_FIXBANNER_REQUEST = "UPDATE_FIXBANNER_REQUEST";
export const UPDATE_FIXBANNER_SUCCESS = "UPDATE_FIXBANNER_SUCCESS";
export const UPDATE_FIXBANNER_FAIL = "UPDATE_FIXBANNER_FAIL";

export const DELETE_FIXBANNER_REQUEST = "DELETE_FIXBANNER_REQUEST";
export const DELETE_FIXBANNER_SUCCESS = "DELETE_FIXBANNER_SUCCESS";
export const DELETE_FIXBANNER_FAIL = "DELETE_FIXBANNER_FAIL";

export const GETALL_FIXBANNER_REQUEST = "GETALL_FIXBANNER_REQUEST";
export const GETALL_FIXBANNER_SUCCESS = "GETALL_FIXBANNER_SUCCESS";
export const GETALL_FIXBANNER_FAIL = "GETALL_FIXBANNER_FAIL";

export const GETDETAIL_FIXBANNER_REQUEST = "GETDETAIL_FIXBANNER_REQUEST";
export const GETDETAIL_FIXBANNER_SUCCESS = "GETDETAIL_FIXBANNER_SUCCESS";
export const GETDETAIL_FIXBANNER_FAIL = "GETDETAIL_FIXBANNER_FAIL";

export const FIXBANNER_CHANGE_STATUS_REQUEST =
  "FIXBANNER_CHANGE_STATUS_REQUEST";
export const FIXBANNER_CHANGE_STATUS_SUCCESS =
  "FIXBANNER_CHANGE_STATUS_SUCCESS";
export const FIXBANNER_CHANGE_STATUS_FAIL = "FIXBANNER_CHANGE_STATUS_FAIL";
