// constant files

export const ADD_GENIUSPRODUCT_REQUEST = "ADD_GENIUSPRODUCT_REQUEST";
export const ADD_GENIUSPRODUCT_SUCCESS = "ADD_GENIUSPRODUCT_SUCCESS";
export const ADD_GENIUSPRODUCT_FAIL = "ADD_GENIUSPRODUCT_FAIL";

export const UPDATE_GENIUSPRODUCT_REQUEST = "UPDATE_GENIUSPRODUCT_REQUEST";
export const UPDATE_GENIUSPRODUCT_SUCCESS = "UPDATE_GENIUSPRODUCT_SUCCESS";
export const UPDATE_GENIUSPRODUCT_FAIL = "UPDATE_GENIUSPRODUCT_FAIL";

export const DELETE_GENIUSPRODUCT_REQUEST = "DELETE_GENIUSPRODUCT_REQUEST";
export const DELETE_GENIUSPRODUCT_SUCCESS = "DELETE_GENIUSPRODUCT_SUCCESS";
export const DELETE_GENIUSPRODUCT_FAIL = "DELETE_GENIUSPRODUCT_FAIL";

export const GETALL_GENIUSPRODUCT_REQUEST = "GETALL_GENIUSPRODUCT_REQUEST";
export const GETALL_GENIUSPRODUCT_SUCCESS = "GETALL_GENIUSPRODUCT_SUCCESS";
export const GETALL_GENIUSPRODUCT_FAIL = "GETALL_GENIUSPRODUCT_FAIL";

export const GETDETAIL_GENIUSPRODUCT_REQUEST = "GETDETAIL_GENIUSPRODUCT_REQUEST";
export const GETDETAIL_GENIUSPRODUCT_SUCCESS = "GETDETAIL_GENIUSPRODUCT_SUCCESS";
export const GETDETAIL_GENIUSPRODUCT_FAIL = "GETDETAIL_GENIUSPRODUCT_FAIL";

export const GENIUSPRODUCT_CHANGE_STATUS_REQUEST =
  "GENIUSPRODUCT_CHANGE_STATUS_REQUEST";
export const GENIUSPRODUCT_CHANGE_STATUS_SUCCESS =
  "GENIUSPRODUCT_CHANGE_STATUS_SUCCESS";
export const GENIUSPRODUCT_CHANGE_STATUS_FAIL = "GENIUSPRODUCT_CHANGE_STATUS_FAIL";
