export const GET_USERS_COUNT_REQUEST = "GET_USERS_COUNT_REQUEST";
export const GET_USERS_COUNT_SUCCESS = "GET_USERS_COUNT_SUCCESS";
export const GET_USERS_COUNT_FAIL = "GET_USERS_COUNT_FAIL";

export const GET_MAIN_PRODUCT_COUNT_REQUEST = "GET_MAIN_PRODUCT_COUNT_REQUEST";
export const GET_MAIN_PRODUCT_COUNT_SUCCESS = "GET_MAIN_PRODUCT_COUNT_SUCCESS";
export const GET_MAIN_PRODUCT_COUNT_FAIL = "GET_MAIN_PRODUCT_COUNT_FAIL";

export const GET_ACCESSORY_PRODUCT_COUNT_REQUEST =
  "GET_ACCESSORY_PRODUCT_COUNT_REQUEST";
export const GET_ACCESSORY_PRODUCT_COUNT_SUCCESS =
  "GET_ACCESSORY_PRODUCT_COUNT_SUCCESS";
export const GET_ACCESSORY_PRODUCT_COUNT_FAIL =
  "GET_ACCESSORY_PRODUCT_COUNT_FAIL";

export const GET_ALL_ORDER_COUNT_REQUEST = "GET_ALL_ORDER_COUNT_REQUEST";
export const GET_ALL_ORDER_COUNT_SUCCESS = "GET_ALL_ORDER_COUNT_SUCCESS";
export const GET_ALL_ORDER_COUNT_FAIL = "GET_ALL_ORDER_COUNT_FAIL";

export const GET_CANCEL_ORDER_COUNT_REQUEST = "GET_CANCEL_ORDER_COUNT_REQUEST";
export const GET_CANCEL_ORDER_COUNT_SUCCESS = "GET_CANCEL_ORDER_COUNT_SUCCESS";
export const GET_CANCEL_ORDER_COUNT_FAIL = "GET_CANCEL_ORDER_COUNT_FAIL";

export const GET_COMPLETE_ORDER_COUNT_REQUEST =
  "GET_COMPLETE_ORDER_COUNT_REQUEST";
export const GET_COMPLETE_ORDER_COUNT_SUCCESS =
  "GET_COMPLETE_ORDER_COUNT_SUCCESS";
export const GET_COMPLETE_ORDER_COUNT_FAIL = "GET_COMPLETE_ORDER_COUNT_FAIL";

export const GET_RETURN_ORDER_COUNT_REQUEST = "GET_RETURN_ORDER_COUNT_REQUEST";
export const GET_RETURN_ORDER_COUNT_SUCCESS = "GET_RETURN_ORDER_COUNT_SUCCESS";
export const GET_RETURN_ORDER_COUNT_FAIL = "GET_RETURN_ORDER_COUNT_FAIL";

export const GET_SALSE_REVENEW_REQUEST = "GET_SALSE_REVENEW_REQUEST";
export const GET_SALSE_REVENEW_SUCCESS = "GET_SALSE_REVENEW_SUCCESS";
export const GET_SALSE_REVENEW_FAIL = "GET_SALSE_REVENEW_FAIL";

export const GET_TODAY_SALSE_REVENEW_REQUEST =
  "GET_TODAY_SALSE_REVENEW_REQUEST";
export const GET_TODAY_SALSE_REVENEW_SUCCESS =
  "GET_TODAY_SALSE_REVENEW_SUCCESS";
export const GET_TODAY_SALSE_REVENEW_FAIL = "GET_TODAY_SALSE_REVENEW_FAIL";

export const GET_7DAY_SALSE_REVENEW_REQUEST = "GET_7DAY_SALSE_REVENEW_REQUEST";
export const GET_7DAY_SALSE_REVENEW_SUCCESS = "GET_7DAY_SALSE_REVENEW_SUCCESS";
export const GET_7DAY_SALSE_REVENEW_FAIL = "GET_7DAY_SALSE_REVENEW_FAIL";

export const GET_30DAY_SALSE_REVENEW_REQUEST =
  "GET_30DAY_SALSE_REVENEW_REQUEST";
export const GET_30DAY_SALSE_REVENEW_SUCCESS =
  "GET_30DAY_SALSE_REVENEW_SUCCESS";
export const GET_30DAY_SALSE_REVENEW_FAIL = "GET_30DAY_SALSE_REVENEW_FAIL";
