// constant files

export const ADD_MAIN_CATEGORY_REQUEST = "ADD_MAIN_CATEGORY_REQUEST";
export const ADD_MAIN_CATEGORY_SUCCESS = "ADD_MAIN_CATEGORY_SUCCESS";
export const ADD_MAIN_CATEGORY_FAIL = "ADD_MAIN_CATEGORY_FAIL";

export const UPDATE_MAIN_CATEGORY_REQUEST = "UPDATE_MAIN_CATEGORY_REQUEST";
export const UPDATE_MAIN_CATEGORY_SUCCESS = "UPDATE_MAIN_CATEGORY_SUCCESS";
export const UPDATE_MAIN_CATEGORY_FAIL = "UPDATE_MAIN_CATEGORY_FAIL";

export const DELETE_MAIN_CATEGORY_REQUEST = "DELETE_MAIN_CATEGORY_REQUEST";
export const DELETE_MAIN_CATEGORY_SUCCESS = "DELETE_MAIN_CATEGORY_SUCCESS";
export const DELETE_MAIN_CATEGORY_FAIL = "DELETE_MAIN_CATEGORY_FAIL";

export const GETALL_MAIN_CATEGORY_REQUEST = "GETALL_MAIN_CATEGORY_REQUEST";
export const GETALL_MAIN_CATEGORY_SUCCESS = "GETALL_MAIN_CATEGORY_SUCCESS";
export const GETALL_MAIN_CATEGORY_FAIL = "GETALL_MAIN_CATEGORY_FAIL";

export const GETDETAIL_MAIN_CATEGORY_REQUEST = "GETDETAIL_MAIN_CATEGORY_REQUEST";
export const GETDETAIL_MAIN_CATEGORY_SUCCESS = "GETDETAIL_MAIN_CATEGORY_SUCCESS";
export const GETDETAIL_MAIN_CATEGORY_FAIL = "GETDETAIL_MAIN_CATEGORY_FAIL";

export const MAIN_CATEGORY_CHANGE_STATUS_REQUEST = "MAIN_CATEGORY_CHANGE_STATUS_REQUEST";
export const MAIN_CATEGORY_CHANGE_STATUS_SUCCESS = "MAIN_CATEGORY_CHANGE_STATUS_SUCCESS";
export const MAIN_CATEGORY_CHANGE_STATUS_FAIL = "MAIN_CATEGORY_CHANGE_STATUS_FAIL";
