// constant files

export const ADD_OFFER_PRODUCT_REQUEST = "ADD_OFFER_PRODUCT_REQUEST";
export const ADD_OFFER_PRODUCT_SUCCESS = "ADD_OFFER_PRODUCT_SUCCESS";
export const ADD_OFFER_PRODUCT_FAIL = "ADD_OFFER_PRODUCT_FAIL";

export const UPDATE_OFFER_PRODUCT_REQUEST = "UPDATE_OFFER_PRODUCT_REQUEST";
export const UPDATE_OFFER_PRODUCT_SUCCESS = "UPDATE_OFFER_PRODUCT_SUCCESS";
export const UPDATE_OFFER_PRODUCT_FAIL = "UPDATE_OFFER_PRODUCT_FAIL";

export const DELETE_OFFER_PRODUCT_REQUEST = "DELETE_OFFER_PRODUCT_REQUEST";
export const DELETE_OFFER_PRODUCT_SUCCESS = "DELETE_OFFER_PRODUCT_SUCCESS";
export const DELETE_OFFER_PRODUCT_FAIL = "DELETE_OFFER_PRODUCT_FAIL";

export const GET_ALL_OFFER_PRODUCT_REQUEST = "GET_ALL_OFFER_PRODUCT_REQUEST";
export const GET_ALL_OFFER_PRODUCT_SUCCESS = "GET_ALL_OFFER_PRODUCT_SUCCESS";
export const GET_ALL_OFFER_PRODUCT_FAIL = "GET_ALL_OFFER_PRODUCT_FAIL";

export const GET_SINGLE_OFFER_PRODUCT_REQUEST =
  "GET_SINGLE_OFFER_PRODUCT_REQUEST";
export const GET_SINGLE_OFFER_PRODUCT_SUCCESS =
  "GET_SINGLE_OFFER_PRODUCT_SUCCESS";
export const GET_SINGLE_OFFER_PRODUCT_FAIL = "GET_SINGLE_OFFER_PRODUCT_FAIL";

export const OFFER_PRODUCT_CHANGE_STATUS_REQUEST =
  "OFFER_PRODUCT_CHANGE_STATUS_REQUEST";
export const OFFER_PRODUCT_CHANGE_STATUS_SUCCESS =
  "OFFER_PRODUCT_CHANGE_STATUS_SUCCESS";
export const OFFER_PRODUCT_CHANGE_STATUS_FAIL =
  "OFFER_PRODUCT_CHANGE_STATUS_FAIL";

export const USER_IS_OFFER_REQUEST = "USER_IS_OFFER_REQUEST";
export const USER_IS_OFFER_SUCCESS = "USER_IS_OFFER_SUCCESS";
export const USER_IS_OFFER_FAIL = "USER_IS_OFFER_FAIL";
