// constant files

export const ADD_OFFER_CODE_REQUEST = "ADD_OFFER_CODE_REQUEST";
export const ADD_OFFER_CODE_SUCCESS = "ADD_OFFER_CODE_SUCCESS";
export const ADD_OFFER_CODE_FAIL = "ADD_OFFER_CODE_FAIL";

export const UPDATE_OFFER_CODE_REQUEST = "UPDATE_OFFER_CODE_REQUEST";
export const UPDATE_OFFER_CODE_SUCCESS = "UPDATE_OFFER_CODE_SUCCESS";
export const UPDATE_OFFER_CODE_FAIL = "UPDATE_OFFER_CODE_FAIL";

export const DELETE_OFFER_CODE_REQUEST = "DELETE_OFFER_CODE_REQUEST";
export const DELETE_OFFER_CODE_SUCCESS = "DELETE_OFFER_CODE_SUCCESS";
export const DELETE_OFFER_CODE_FAIL = "DELETE_OFFER_CODE_FAIL";

export const GET_ALL_OFFER_CODE_REQUEST = "GET_ALL_OFFER_CODE_REQUEST";
export const GET_ALL_OFFER_CODE_SUCCESS = "GET_ALL_OFFER_CODE_SUCCESS";
export const GET_ALL_OFFER_CODE_FAIL = "GET_ALL_OFFER_CODE_FAIL";

export const GET_SINGLE_OFFER_CODE_REQUEST = "GET_SINGLE_OFFER_CODE_REQUEST";
export const GET_SINGLE_OFFER_CODE_SUCCESS = "GET_SINGLE_OFFER_CODE_SUCCESS";
export const GET_SINGLE_OFFER_CODE_FAIL = "GET_SINGLE_OFFER_CODE_FAIL";

export const OFFER_CODE_CHANGE_STATUS_REQUEST = "OFFER_CODE_CHANGE_STATUS_REQUEST";
export const OFFER_CODE_CHANGE_STATUS_SUCCESS = "OFFER_CODE_CHANGE_STATUS_SUCCESS";
export const OFFER_CODE_CHANGE_STATUS_FAIL = "OFFER_CODE_CHANGE_STATUS_FAIL";
