// constant files

export const ADD_OFFERCONTENT_REQUEST = "ADD_OFFERCONTENT_REQUEST";
export const ADD_OFFERCONTENT_SUCCESS = "ADD_OFFERCONTENT_SUCCESS";
export const ADD_OFFERCONTENT_FAIL = "ADD_OFFERCONTENT_FAIL";

export const UPDATE_OFFERCONTENT_REQUEST = "UPDATE_OFFERCONTENT_REQUEST";
export const UPDATE_OFFERCONTENT_SUCCESS = "UPDATE_OFFERCONTENT_SUCCESS";
export const UPDATE_OFFERCONTENT_FAIL = "UPDATE_OFFERCONTENT_FAIL";

export const DELETE_OFFERCONTENT_REQUEST = "DELETE_OFFERCONTENT_REQUEST";
export const DELETE_OFFERCONTENT_SUCCESS = "DELETE_OFFERCONTENT_SUCCESS";
export const DELETE_OFFERCONTENT_FAIL = "DELETE_OFFERCONTENT_FAIL";

export const GETALL_OFFERCONTENT_REQUEST = "GETALL_OFFERCONTENT_REQUEST";
export const GETALL_OFFERCONTENT_SUCCESS = "GETALL_OFFERCONTENT_SUCCESS";
export const GETALL_OFFERCONTENT_FAIL = "GETALL_OFFERCONTENT_FAIL";

export const GETDETAIL_OFFERCONTENT_REQUEST = "GETDETAIL_OFFERCONTENT_REQUEST";
export const GETDETAIL_OFFERCONTENT_SUCCESS = "GETDETAIL_OFFERCONTENT_SUCCESS";
export const GETDETAIL_OFFERCONTENT_FAIL = "GETDETAIL_OFFERCONTENT_FAIL";

export const OFFERCONTENT_CHANGE_STATUS_REQUEST =
  "OFFERCONTENT_CHANGE_STATUS_REQUEST";
export const OFFERCONTENT_CHANGE_STATUS_SUCCESS =
  "OFFERCONTENT_CHANGE_STATUS_SUCCESS";
export const OFFERCONTENT_CHANGE_STATUS_FAIL =
  "OFFERCONTENT_CHANGE_STATUS_FAIL";
