// constant files

export const ADD_ORDER_REVIEW_REQUEST = "ADD_ORDER_REVIEW_REQUEST";
export const ADD_ORDER_REVIEW_SUCCESS = "ADD_ORDER_REVIEW_SUCCESS";
export const ADD_ORDER_REVIEW_FAIL = "ADD_ORDER_REVIEW_FAIL";

export const UPDATE_ORDER_REVIEW_REQUEST = "UPDATE_ORDER_REVIEW_REQUEST";
export const UPDATE_ORDER_REVIEW_SUCCESS = "UPDATE_ORDER_REVIEW_SUCCESS";
export const UPDATE_ORDER_REVIEW_FAIL = "UPDATE_ORDER_REVIEW_FAIL";

export const DELETE_ORDER_REVIEW_REQUEST = "DELETE_ORDER_REVIEW_REQUEST";
export const DELETE_ORDER_REVIEW_SUCCESS = "DELETE_ORDER_REVIEW_SUCCESS";
export const DELETE_ORDER_REVIEW_FAIL = "DELETE_ORDER_REVIEW_FAIL";

export const GET_ALL_ORDER_REVIEW_REQUEST = "GET_ALL_ORDER_REVIEW_REQUEST";
export const GET_ALL_ORDER_REVIEW_SUCCESS = "GET_ALL_ORDER_REVIEW_SUCCESS";
export const GET_ALL_ORDER_REVIEW_FAIL = "GET_ALL_ORDER_REVIEW_FAIL";

export const GET_SINGLE_ORDER_REVIEW_REQUEST = "GET_SINGLE_ORDER_REVIEW_REQUEST";
export const GET_SINGLE_ORDER_REVIEW_SUCCESS = "GET_SINGLE_ORDER_REVIEW_SUCCESS";
export const GET_SINGLE_ORDER_REVIEW_FAIL = "GET_SINGLE_ORDER_REVIEW_FAIL";

export const ORDER_REVIEW_CHANGE_STATUS_REQUEST = "ORDER_REVIEW_CHANGE_STATUS_REQUEST";
export const ORDER_REVIEW_CHANGE_STATUS_SUCCESS = "ORDER_REVIEW_CHANGE_STATUS_SUCCESS";
export const ORDER_REVIEW_CHANGE_STATUS_FAIL = "ORDER_REVIEW_CHANGE_STATUS_FAIL";
