// constant files

export const ADD_ORDER_STATUS_REQUEST = "ADD_ORDER_STATUS_REQUEST";
export const ADD_ORDER_STATUS_SUCCESS = "ADD_ORDER_STATUS_SUCCESS";
export const ADD_ORDER_STATUS_FAIL = "ADD_ORDER_STATUS_FAIL";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL";

export const DELETE_ORDER_STATUS_REQUEST = "DELETE_ORDER_STATUS_REQUEST";
export const DELETE_ORDER_STATUS_SUCCESS = "DELETE_ORDER_STATUS_SUCCESS";
export const DELETE_ORDER_STATUS_FAIL = "DELETE_ORDER_STATUS_FAIL";

export const GET_ALL_ORDER_STATUS_REQUEST = "GET_ALL_ORDER_STATUS_REQUEST";
export const GET_ALL_ORDER_STATUS_SUCCESS = "GET_ALL_ORDER_STATUS_SUCCESS";
export const GET_ALL_ORDER_STATUS_FAIL = "GET_ALL_ORDER_STATUS_FAIL";

export const GET_SINGLE_ORDER_STATUS_REQUEST =
  "GET_SINGLE_ORDER_STATUS_REQUEST";
export const GET_SINGLE_ORDER_STATUS_SUCCESS =
  "GET_SINGLE_ORDER_STATUS_SUCCESS";
export const GET_SINGLE_ORDER_STATUS_FAIL = "GET_SINGLE_ORDER_STATUS_FAIL";

export const ORDER_STATUS_CHANGE_STATUS_REQUEST =
  "ORDER_STATUS_CHANGE_STATUS_REQUEST";
export const ORDER_STATUS_CHANGE_STATUS_SUCCESS =
  "ORDER_STATUS_CHANGE_STATUS_SUCCESS";
export const ORDER_STATUS_CHANGE_STATUS_FAIL =
  "ORDER_STATUS_CHANGE_STATUS_FAIL";
