// constant files

export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

export const GET_ALL_ORDER_REQUEST = "GET_ALL_ORDER_REQUEST";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_FAIL = "GET_ALL_ORDER_FAIL";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const GET_SINGLE_ORDER_REQUEST = "GET_SINGLE_ORDER_REQUEST";
export const GET_SINGLE_ORDER_SUCCESS = "GET_SINGLE_ORDER_SUCCESS";
export const GET_SINGLE_ORDER_FAIL = "GET_SINGLE_ORDER_FAIL";

export const GET_ALL_ORDERLIST_REQUEST = "GET_ALL_ORDERLIST_REQUEST";
export const GET_ALL_ORDERLIST_SUCCESS = "GET_ALL_ORDERLIST_SUCCESS";
export const GET_ALL_ORDERLIST_FAIL = "GET_ALL_ORDERLIST_FAIL";

export const GET_SINGLE_ORDERLIST_REQUEST = "GET_SINGLE_ORDERLIST_REQUEST";
export const GET_SINGLE_ORDERLIST_SUCCESS = "GET_SINGLE_ORDERLIST_SUCCESS";
export const GET_SINGLE_ORDERLIST_FAIL = "GET_SINGLE_ORDERLIST_FAIL";

export const ORDER_CHANGE_STATUS_REQUEST = "ORDER_CHANGE_STATUS_REQUEST";
export const ORDER_CHANGE_STATUS_SUCCESS = "ORDER_CHANGE_STATUS_SUCCESS";
export const ORDER_CHANGE_STATUS_FAIL = "ORDER_CHANGE_STATUS_FAIL";

export const CANCEL_ORDER_LIST_REQUEST = "CANCEL_ORDER_LIST_REQUEST";
export const CANCEL_ORDER_LIST_SUCCESS = "CANCEL_ORDER_LIST_SUCCESS";
export const CANCEL_ORDER_LIST_FAIL = "CANCEL_ORDER_LIST_FAIL";

export const RETURN_ORDER_LIST_REQUEST = "RETURN_ORDER_LIST_REQUEST";
export const RETURN_ORDER_LIST_SUCCESS = "RETURN_ORDER_LIST_SUCCESS";
export const RETURN_ORDER_LIST_FAIL = "RETURN_ORDER_LIST_FAIL";

export const CANCEL_ORDER_DETAIL_REQUEST = "CANCEL_ORDER_DETAIL_REQUEST";
export const CANCEL_ORDER_DETAIL_SUCCESS = "CANCEL_ORDER_DETAIL_SUCCESS";
export const CANCEL_ORDER_DETAIL_FAIL = "CANCEL_ORDER_DETAIL_FAIL";

export const RETURN_ORDER_DETAIL_REQUEST = "RETURN_ORDER_DETAIL_REQUEST";
export const RETURN_ORDER_DETAIL_SUCCESS = "RETURN_ORDER_DETAIL_SUCCESS";
export const RETURN_ORDER_DETAIL_FAIL = "RETURN_ORDER_DETAIL_FAIL";

export const APPROVE_RETURN_ORDER_REQUEST = "APPROVE_RETURN_ORDER_REQUEST";
export const APPROVE_RETURN_ORDER_SUCCESS = "APPROVE_RETURN_ORDER_SUCCESS";
export const APPROVE_RETURN_ORDER_FAIL = "APPROVE_RETURN_ORDER_FAIL";

export const APPROVE_CANCEL_ORDER_REQUEST = "APPROVE_CANCEL_ORDER_REQUEST";
export const APPROVE_CANCEL_ORDER_SUCCESS = "APPROVE_CANCEL_ORDER_SUCCESS";
export const APPROVE_CANCEL_ORDER_FAIL = "APPROVE_CANCEL_ORDER_FAIL";
