// constant files

export const ADD_PRIVACYPOLICY_REQUEST = "ADD_PRIVACYPOLICY_REQUEST";
export const ADD_PRIVACYPOLICY_SUCCESS = "ADD_PRIVACYPOLICY_SUCCESS";
export const ADD_PRIVACYPOLICY_FAIL = "ADD_PRIVACYPOLICY_FAIL";

export const UPDATE_PRIVACYPOLICY_REQUEST = "UPDATE_PRIVACYPOLICY_REQUEST";
export const UPDATE_PRIVACYPOLICY_SUCCESS = "UPDATE_PRIVACYPOLICY_SUCCESS";
export const UPDATE_PRIVACYPOLICY_FAIL = "UPDATE_PRIVACYPOLICY_FAIL";

export const DELETE_PRIVACYPOLICY_REQUEST = "DELETE_PRIVACYPOLICY_REQUEST";
export const DELETE_PRIVACYPOLICY_SUCCESS = "DELETE_PRIVACYPOLICY_SUCCESS";
export const DELETE_PRIVACYPOLICY_FAIL = "DELETE_PRIVACYPOLICY_FAIL";

export const GETALL_PRIVACYPOLICY_REQUEST = "GETALL_PRIVACYPOLICY_REQUEST";
export const GETALL_PRIVACYPOLICY_SUCCESS = "GETALL_PRIVACYPOLICY_SUCCESS";
export const GETALL_PRIVACYPOLICY_FAIL = "GETALL_PRIVACYPOLICY_FAIL";

export const GETDETAIL_PRIVACYPOLICY_REQUEST = "GETDETAIL_PRIVACYPOLICY_REQUEST";
export const GETDETAIL_PRIVACYPOLICY_SUCCESS = "GETDETAIL_PRIVACYPOLICY_SUCCESS";
export const GETDETAIL_PRIVACYPOLICY_FAIL = "GETDETAIL_PRIVACYPOLICY_FAIL";

export const PRIVACYPOLICY_CHANGE_STATUS_REQUEST =
  "PRIVACYPOLICY_CHANGE_STATUS_REQUEST";
export const PRIVACYPOLICY_CHANGE_STATUS_SUCCESS =
  "PRIVACYPOLICY_CHANGE_STATUS_SUCCESS";
export const PRIVACYPOLICY_CHANGE_STATUS_FAIL = "PRIVACYPOLICY_CHANGE_STATUS_FAIL";
