// constant files

export const ADD_PRODUCT_RATING_REQUEST = "ADD_PRODUCT_RATING_REQUEST";
export const ADD_PRODUCT_RATING_SUCCESS = "ADD_PRODUCT_RATING_SUCCESS";
export const ADD_PRODUCT_RATING_FAIL = "ADD_PRODUCT_RATING_FAIL";

export const UPDATE_PRODUCT_RATING_REQUEST = "UPDATE_PRODUCT_RATING_REQUEST";
export const UPDATE_PRODUCT_RATING_SUCCESS = "UPDATE_PRODUCT_RATING_SUCCESS";
export const UPDATE_PRODUCT_RATING_FAIL = "UPDATE_PRODUCT_RATING_FAIL";

export const DELETE_PRODUCT_RATING_REQUEST = "DELETE_PRODUCT_RATING_REQUEST";
export const DELETE_PRODUCT_RATING_SUCCESS = "DELETE_PRODUCT_RATING_SUCCESS";
export const DELETE_PRODUCT_RATING_FAIL = "DELETE_PRODUCT_RATING_FAIL";

export const GET_ALL_PRODUCT_RATING_REQUEST = "GET_ALL_PRODUCT_RATING_REQUEST";
export const GET_ALL_PRODUCT_RATING_SUCCESS = "GET_ALL_PRODUCT_RATING_SUCCESS";
export const GET_ALL_PRODUCT_RATING_FAIL = "GET_ALL_PRODUCT_RATING_FAIL";

export const GET_SINGLE_PRODUCT_RATING_REQUEST = "GET_SINGLE_PRODUCT_RATING_REQUEST";
export const GET_SINGLE_PRODUCT_RATING_SUCCESS = "GET_SINGLE_PRODUCT_RATING_SUCCESS";
export const GET_SINGLE_PRODUCT_RATING_FAIL = "GET_SINGLE_PRODUCT_RATING_FAIL";

export const PRODUCT_RATING_CHANGE_STATUS_REQUEST = "PRODUCT_RATING_CHANGE_STATUS_REQUEST";
export const PRODUCT_RATING_CHANGE_STATUS_SUCCESS = "PRODUCT_RATING_CHANGE_STATUS_SUCCESS";
export const PRODUCT_RATING_CHANGE_STATUS_FAIL = "PRODUCT_RATING_CHANGE_STATUS_FAIL";
