// constant files

export const ADD_PRODUCT_IMAGE_REQUEST = "ADD_PRODUCT_IMAGE_REQUEST";
export const ADD_PRODUCT_IMAGE_SUCCESS = "ADD_PRODUCT_IMAGE_SUCCESS";
export const ADD_PRODUCT_IMAGE_FAIL = "ADD_PRODUCT_IMAGE_FAIL";

export const UPDATE_PRODUCT_IMAGE_REQUEST = "UPDATE_PRODUCT_IMAGE_REQUEST";
export const UPDATE_PRODUCT_IMAGE_SUCCESS = "UPDATE_PRODUCT_IMAGE_SUCCESS";
export const UPDATE_PRODUCT_IMAGE_FAIL = "UPDATE_PRODUCT_IMAGE_FAIL";

export const DELETE_PRODUCT_IMAGE_REQUEST = "DELETE_PRODUCT_IMAGE_REQUEST";
export const DELETE_PRODUCT_IMAGE_SUCCESS = "DELETE_PRODUCT_IMAGE_SUCCESS";
export const DELETE_PRODUCT_IMAGE_FAIL = "DELETE_PRODUCT_IMAGE_FAIL";

export const GET_ALL_PRODUCT_IMAGE_REQUEST = "GET_ALL_PRODUCT_IMAGE_REQUEST";
export const GET_ALL_PRODUCT_IMAGE_SUCCESS = "GET_ALL_PRODUCT_IMAGE_SUCCESS";
export const GET_ALL_PRODUCT_IMAGE_FAIL = "GET_ALL_PRODUCT_IMAGE_FAIL";

export const GET_SINGLE_PRODUCT_IMAGE_REQUEST = "GET_SINGLE_PRODUCT_IMAGE_REQUEST";
export const GET_SINGLE_PRODUCT_IMAGE_SUCCESS = "GET_SINGLE_PRODUCT_IMAGE_SUCCESS";
export const GET_SINGLE_PRODUCT_IMAGE_FAIL = "GET_SINGLE_PRODUCT_IMAGE_FAIL";

export const PRODUCT_IMAGE_CHANGE_STATUS_REQUEST = "PRODUCT_IMAGE_CHANGE_STATUS_REQUEST";
export const PRODUCT_IMAGE_CHANGE_STATUS_SUCCESS = "PRODUCT_IMAGE_CHANGE_STATUS_SUCCESS";
export const PRODUCT_IMAGE_CHANGE_STATUS_FAIL = "PRODUCT_IMAGE_CHANGE_STATUS_FAIL";
