// constant files

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const GET_ALL_PRODUCT_SUBCATID_REQUEST =
  "GET_ALL_PRODUCT_SUBCATID_REQUEST";
export const GET_ALL_PRODUCT_SUBCATID_SUCCESS =
  "GET_ALL_PRODUCT_SUBCATID_SUCCESS";
export const GET_ALL_PRODUCT_SUBCATID_FAIL = "GET_ALL_PRODUCT_SUBCATID_FAIL";

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAIL = "GET_SINGLE_PRODUCT_FAIL";

export const PRODUCT_CHANGE_STATUS_REQUEST = "PRODUCT_CHANGE_STATUS_REQUEST";
export const PRODUCT_CHANGE_STATUS_SUCCESS = "PRODUCT_CHANGE_STATUS_SUCCESS";
export const PRODUCT_CHANGE_STATUS_FAIL = "PRODUCT_CHANGE_STATUS_FAIL";
