// constant files

export const ADD_PRODUCT_DETAIL_REQUEST = "ADD_PRODUCT_DETAIL_REQUEST";
export const ADD_PRODUCT_DETAIL_SUCCESS = "ADD_PRODUCT_DETAIL_SUCCESS";
export const ADD_PRODUCT_DETAIL_FAIL = "ADD_PRODUCT_DETAIL_FAIL";

export const UPDATE_PRODUCT_DETAIL_REQUEST = "UPDATE_PRODUCT_DETAIL_REQUEST";
export const UPDATE_PRODUCT_DETAIL_SUCCESS = "UPDATE_PRODUCT_DETAIL_SUCCESS";
export const UPDATE_PRODUCT_DETAIL_FAIL = "UPDATE_PRODUCT_DETAIL_FAIL";

export const DELETE_PRODUCT_DETAIL_REQUEST = "DELETE_PRODUCT_DETAIL_REQUEST";
export const DELETE_PRODUCT_DETAIL_SUCCESS = "DELETE_PRODUCT_DETAIL_SUCCESS";
export const DELETE_PRODUCT_DETAIL_FAIL = "DELETE_PRODUCT_DETAIL_FAIL";

export const GET_ALL_PRODUCT_DETAIL_REQUEST = "GET_ALL_PRODUCT_DETAIL_REQUEST";
export const GET_ALL_PRODUCT_DETAIL_SUCCESS = "GET_ALL_PRODUCT_DETAIL_SUCCESS";
export const GET_ALL_PRODUCT_DETAIL_FAIL = "GET_ALL_PRODUCT_DETAIL_FAIL";

export const GET_SINGLE_PRODUCT_DETAIL_REQUEST = "GET_SINGLE_PRODUCT_DETAIL_REQUEST";
export const GET_SINGLE_PRODUCT_DETAIL_SUCCESS = "GET_SINGLE_PRODUCT_DETAIL_SUCCESS";
export const GET_SINGLE_PRODUCT_DETAIL_FAIL = "GET_SINGLE_PRODUCT_DETAIL_FAIL";

export const PRODUCT_DETAIL_CHANGE_STATUS_REQUEST = "PRODUCT_DETAIL_CHANGE_STATUS_REQUEST";
export const PRODUCT_DETAIL_CHANGE_STATUS_SUCCESS = "PRODUCT_DETAIL_CHANGE_STATUS_SUCCESS";
export const PRODUCT_DETAIL_CHANGE_STATUS_FAIL = "PRODUCT_DETAIL_CHANGE_STATUS_FAIL";
