// constant files

export const ADD_PROMO_CODE_REQUEST = "ADD_PROMO_CODE_REQUEST";
export const ADD_PROMO_CODE_SUCCESS = "ADD_PROMO_CODE_SUCCESS";
export const ADD_PROMO_CODE_FAIL = "ADD_PROMO_CODE_FAIL";

export const UPDATE_PROMO_CODE_REQUEST = "UPDATE_PROMO_CODE_REQUEST";
export const UPDATE_PROMO_CODE_SUCCESS = "UPDATE_PROMO_CODE_SUCCESS";
export const UPDATE_PROMO_CODE_FAIL = "UPDATE_PROMO_CODE_FAIL";

export const DELETE_PROMO_CODE_REQUEST = "DELETE_PROMO_CODE_REQUEST";
export const DELETE_PROMO_CODE_SUCCESS = "DELETE_PROMO_CODE_SUCCESS";
export const DELETE_PROMO_CODE_FAIL = "DELETE_PROMO_CODE_FAIL";

export const GET_ALL_PROMO_CODE_REQUEST = "GET_ALL_PROMO_CODE_REQUEST";
export const GET_ALL_PROMO_CODE_SUCCESS = "GET_ALL_PROMO_CODE_SUCCESS";
export const GET_ALL_PROMO_CODE_FAIL = "GET_ALL_PROMO_CODE_FAIL";

export const GET_SINGLE_PROMO_CODE_REQUEST = "GET_SINGLE_PROMO_CODE_REQUEST";
export const GET_SINGLE_PROMO_CODE_SUCCESS = "GET_SINGLE_PROMO_CODE_SUCCESS";
export const GET_SINGLE_PROMO_CODE_FAIL = "GET_SINGLE_PROMO_CODE_FAIL";

export const PROMO_CODE_CHANGE_STATUS_REQUEST = "PROMO_CODE_CHANGE_STATUS_REQUEST";
export const PROMO_CODE_CHANGE_STATUS_SUCCESS = "PROMO_CODE_CHANGE_STATUS_SUCCESS";
export const PROMO_CODE_CHANGE_STATUS_FAIL = "PROMO_CODE_CHANGE_STATUS_FAIL";
