// constant files

export const ADD_PROS_REQUEST = "ADD_PROS_REQUEST";
export const ADD_PROS_SUCCESS = "ADD_PROS_SUCCESS";
export const ADD_PROS_FAIL = "ADD_PROS_FAIL";

export const UPDATE_PROS_REQUEST = "UPDATE_PROS_REQUEST";
export const UPDATE_PROS_SUCCESS = "UPDATE_PROS_SUCCESS";
export const UPDATE_PROS_FAIL = "UPDATE_PROS_FAIL";

export const DELETE_PROS_REQUEST = "DELETE_PROS_REQUEST";
export const DELETE_PROS_SUCCESS = "DELETE_PROS_SUCCESS";
export const DELETE_PROS_FAIL = "DELETE_PROS_FAIL";

export const GET_ALL_PROS_REQUEST = "GET_ALL_PROS_REQUEST";
export const GET_ALL_PROS_SUCCESS = "GET_ALL_PROS_SUCCESS";
export const GET_ALL_PROS_FAIL = "GET_ALL_PROS_FAIL";

export const GET_SINGLE_PROS_REQUEST = "GET_SINGLE_PROS_REQUEST";
export const GET_SINGLE_PROS_SUCCESS = "GET_SINGLE_PROS_SUCCESS";
export const GET_SINGLE_PROS_FAIL = "GET_SINGLE_PROS_FAIL";

export const PROS_CHANGE_STATUS_REQUEST = "PROS_CHANGE_STATUS_REQUEST";
export const PROS_CHANGE_STATUS_SUCCESS = "PROS_CHANGE_STATUS_SUCCESS";
export const PROS_CHANGE_STATUS_FAIL = "PROS_CHANGE_STATUS_FAIL";
