// constant files

export const ADD_RETURNPOLICY_REQUEST = "ADD_RETURNPOLICY_REQUEST";
export const ADD_RETURNPOLICY_SUCCESS = "ADD_RETURNPOLICY_SUCCESS";
export const ADD_RETURNPOLICY_FAIL = "ADD_RETURNPOLICY_FAIL";

export const UPDATE_RETURNPOLICY_REQUEST = "UPDATE_RETURNPOLICY_REQUEST";
export const UPDATE_RETURNPOLICY_SUCCESS = "UPDATE_RETURNPOLICY_SUCCESS";
export const UPDATE_RETURNPOLICY_FAIL = "UPDATE_RETURNPOLICY_FAIL";

export const DELETE_RETURNPOLICY_REQUEST = "DELETE_RETURNPOLICY_REQUEST";
export const DELETE_RETURNPOLICY_SUCCESS = "DELETE_RETURNPOLICY_SUCCESS";
export const DELETE_RETURNPOLICY_FAIL = "DELETE_RETURNPOLICY_FAIL";

export const GET_ALL_RETURNPOLICY_REQUEST = "GET_ALL_RETURNPOLICY_REQUEST";
export const GET_ALL_RETURNPOLICY_SUCCESS = "GET_ALL_RETURNPOLICY_SUCCESS";
export const GET_ALL_RETURNPOLICY_FAIL = "GET_ALL_RETURNPOLICY_FAIL";

export const GET_SINGLE_RETURNPOLICY_REQUEST = "GET_SINGLE_RETURNPOLICY_REQUEST";
export const GET_SINGLE_RETURNPOLICY_SUCCESS = "GET_SINGLE_RETURNPOLICY_SUCCESS";
export const GET_SINGLE_RETURNPOLICY_FAIL = "GET_SINGLE_RETURNPOLICY_FAIL";

export const RETURNPOLICY_CHANGE_STATUS_REQUEST = "RETURNPOLICY_CHANGE_STATUS_REQUEST";
export const RETURNPOLICY_CHANGE_STATUS_SUCCESS = "RETURNPOLICY_CHANGE_STATUS_SUCCESS";
export const RETURNPOLICY_CHANGE_STATUS_FAIL = "RETURNPOLICY_CHANGE_STATUS_FAIL";
