// constant files

export const ADD_STATICECONTENT_REQUEST = "ADD_STATICECONTENT_REQUEST";
export const ADD_STATICECONTENT_SUCCESS = "ADD_STATICECONTENT_SUCCESS";
export const ADD_STATICECONTENT_FAIL = "ADD_STATICECONTENT_FAIL";

export const UPDATE_STATICECONTENT_REQUEST = "UPDATE_STATICECONTENT_REQUEST";
export const UPDATE_STATICECONTENT_SUCCESS = "UPDATE_STATICECONTENT_SUCCESS";
export const UPDATE_STATICECONTENT_FAIL = "UPDATE_STATICECONTENT_FAIL";

export const DELETE_STATICECONTENT_REQUEST = "DELETE_STATICECONTENT_REQUEST";
export const DELETE_STATICECONTENT_SUCCESS = "DELETE_STATICECONTENT_SUCCESS";
export const DELETE_STATICECONTENT_FAIL = "DELETE_STATICECONTENT_FAIL";

export const GETALL_STATICECONTENT_REQUEST = "GETALL_STATICECONTENT_REQUEST";
export const GETALL_STATICECONTENT_SUCCESS = "GETALL_STATICECONTENT_SUCCESS";
export const GETALL_STATICECONTENT_FAIL = "GETALL_STATICECONTENT_FAIL";

export const GETDETAIL_STATICECONTENT_REQUEST = "GETDETAIL_STATICECONTENT_REQUEST";
export const GETDETAIL_STATICECONTENT_SUCCESS = "GETDETAIL_STATICECONTENT_SUCCESS";
export const GETDETAIL_STATICECONTENT_FAIL = "GETDETAIL_STATICECONTENT_FAIL";

export const STATICECONTENT_CHANGE_STATUS_REQUEST = "STATICECONTENT_CHANGE_STATUS_REQUEST";
export const STATICECONTENT_CHANGE_STATUS_SUCCESS = "STATICECONTENT_CHANGE_STATUS_SUCCESS";
export const STATICECONTENT_CHANGE_STATUS_FAIL = "STATICECONTENT_CHANGE_STATUS_FAIL";
