// constant files

export const ADD_STORE_REQUEST = "ADD_STORE_REQUEST";
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS";
export const ADD_STORE_FAIL = "ADD_STORE_FAIL";

export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAIL = "UPDATE_STORE_FAIL";

export const DELETE_STORE_REQUEST = "DELETE_STORE_REQUEST";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";
export const DELETE_STORE_FAIL = "DELETE_STORE_FAIL";

export const GET_ALL_STORE_REQUEST = "GET_ALL_STORE_REQUEST";
export const GET_ALL_STORE_SUCCESS = "GET_ALL_STORE_SUCCESS";
export const GET_ALL_STORE_FAIL = "GET_ALL_STORE_FAIL";

export const GET_SINGLE_STORE_REQUEST = "GET_SINGLE_STORE_REQUEST";
export const GET_SINGLE_STORE_SUCCESS = "GET_SINGLE_STORE_SUCCESS";
export const GET_SINGLE_STORE_FAIL = "GET_SINGLE_STORE_FAIL";

export const STORE_CHANGE_STATUS_REQUEST = "STORE_CHANGE_STATUS_REQUEST";
export const STORE_CHANGE_STATUS_SUCCESS = "STORE_CHANGE_STATUS_SUCCESS";
export const STORE_CHANGE_STATUS_FAIL = "STORE_CHANGE_STATUS_FAIL";
