// constant files

export const ADD_SUBCATEGORYCONTENT_REQUEST = "ADD_SUBCATEGORYCONTENT_REQUEST";
export const ADD_SUBCATEGORYCONTENT_SUCCESS = "ADD_SUBCATEGORYCONTENT_SUCCESS";
export const ADD_SUBCATEGORYCONTENT_FAIL = "ADD_SUBCATEGORYCONTENT_FAIL";

export const UPDATE_SUBCATEGORYCONTENT_REQUEST = "UPDATE_SUBCATEGORYCONTENT_REQUEST";
export const UPDATE_SUBCATEGORYCONTENT_SUCCESS = "UPDATE_SUBCATEGORYCONTENT_SUCCESS";
export const UPDATE_SUBCATEGORYCONTENT_FAIL = "UPDATE_SUBCATEGORYCONTENT_FAIL";

export const DELETE_SUBCATEGORYCONTENT_REQUEST = "DELETE_SUBCATEGORYCONTENT_REQUEST";
export const DELETE_SUBCATEGORYCONTENT_SUCCESS = "DELETE_SUBCATEGORYCONTENT_SUCCESS";
export const DELETE_SUBCATEGORYCONTENT_FAIL = "DELETE_SUBCATEGORYCONTENT_FAIL";

export const GETALL_SUBCATEGORYCONTENT_REQUEST = "GETALL_SUBCATEGORYCONTENT_REQUEST";
export const GETALL_SUBCATEGORYCONTENT_SUCCESS = "GETALL_SUBCATEGORYCONTENT_SUCCESS";
export const GETALL_SUBCATEGORYCONTENT_FAIL = "GETALL_SUBCATEGORYCONTENT_FAIL";

export const GETDETAIL_SUBCATEGORYCONTENT_REQUEST =
  "GETDETAIL_SUBCATEGORYCONTENT_REQUEST";
export const GETDETAIL_SUBCATEGORYCONTENT_SUCCESS =
  "GETDETAIL_SUBCATEGORYCONTENT_SUCCESS";
export const GETDETAIL_SUBCATEGORYCONTENT_FAIL = "GETDETAIL_SUBCATEGORYCONTENT_FAIL";

export const SUBCATEGORYCONTENT_CHANGE_STATUS_REQUEST =
  "SUBCATEGORYCONTENT_CHANGE_STATUS_REQUEST";
export const SUBCATEGORYCONTENT_CHANGE_STATUS_SUCCESS =
  "SUBCATEGORYCONTENT_CHANGE_STATUS_SUCCESS";
export const SUBCATEGORYCONTENT_CHANGE_STATUS_FAIL =
  "SUBCATEGORYCONTENT_CHANGE_STATUS_FAIL";
