// constant files

export const ADD_SUBCATEGORY_REQUEST = "ADD_SUBCATEGORY_REQUEST";
export const ADD_SUBCATEGORY_SUCCESS = "ADD_SUBCATEGORY_SUCCESS";
export const ADD_SUBCATEGORY_FAIL = "ADD_SUBCATEGORY_FAIL";

export const UPDATE_SUBCATEGORY_REQUEST = "UPDATE_SUBCATEGORY_REQUEST";
export const UPDATE_SUBCATEGORY_SUCCESS = "UPDATE_SUBCATEGORY_SUCCESS";
export const UPDATE_SUBCATEGORY_FAIL = "UPDATE_SUBCATEGORY_FAIL";

export const DELETE_SUBCATEGORY_REQUEST = "DELETE_SUBCATEGORY_REQUEST";
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS";
export const DELETE_SUBCATEGORY_FAIL = "DELETE_SUBCATEGORY_FAIL";

export const GETALL_SUBCATEGORY_REQUEST = "GETALL_SUBCATEGORY_REQUEST";
export const GETALL_SUBCATEGORY_SUCCESS = "GETALL_SUBCATEGORY_SUCCESS";
export const GETALL_SUBCATEGORY_FAIL = "GETALL_SUBCATEGORY_FAIL";

export const GETDETAIL_SUBCATEGORY_REQUEST = "GETDETAIL_SUBCATEGORY_REQUEST";
export const GETDETAIL_SUBCATEGORY_SUCCESS = "GETDETAIL_SUBCATEGORY_SUCCESS";
export const GETDETAIL_SUBCATEGORY_FAIL = "GETDETAIL_SUBCATEGORY_FAIL";

export const SUBCATEGORY_CHANGE_STATUS_REQUEST =
  "SUBCATEGORY_CHANGE_STATUS_REQUEST";
export const SUBCATEGORY_CHANGE_STATUS_SUCCESS =
  "SUBCATEGORY_CHANGE_STATUS_SUCCESS";
export const SUBCATEGORY_CHANGE_STATUS_FAIL = "SUBCATEGORY_CHANGE_STATUS_FAIL";

export const SUBCATEGORY_GETBYMAIN_CATID_REQUEST =
  "SUBCATEGORY_GETBYMAIN_CATID_REQUEST";
export const SUBCATEGORY_GETBYMAIN_CATID_SUCCESS =
  "SUBCATEGORY_GETBYMAIN_CATID_SUCCESS";
export const SUBCATEGORY_GETBYMAIN_CATID_FAIL =
  "SUBCATEGORY_GETBYMAIN_CATID_FAIL";

export const SUBCATEGORY_GETBY_CATID_REQUEST =
  "SUBCATEGORY_GETBY_CATID_REQUEST";
export const SUBCATEGORY_GETBY_CATID_SUCCESS =
  "SUBCATEGORY_GETBY_CATID_SUCCESS";
export const SUBCATEGORY_GETBY_CATID_FAIL = "SUBCATEGORY_GETBY_CATID_FAIL";
