// constant files

export const ADD_TERMSCONDITION_REQUEST = "ADD_TERMSCONDITION_REQUEST";
export const ADD_TERMSCONDITION_SUCCESS = "ADD_TERMSCONDITION_SUCCESS";
export const ADD_TERMSCONDITION_FAIL = "ADD_TERMSCONDITION_FAIL";

export const UPDATE_TERMSCONDITION_REQUEST = "UPDATE_TERMSCONDITION_REQUEST";
export const UPDATE_TERMSCONDITION_SUCCESS = "UPDATE_TERMSCONDITION_SUCCESS";
export const UPDATE_TERMSCONDITION_FAIL = "UPDATE_TERMSCONDITION_FAIL";

export const DELETE_TERMSCONDITION_REQUEST = "DELETE_TERMSCONDITION_REQUEST";
export const DELETE_TERMSCONDITION_SUCCESS = "DELETE_TERMSCONDITION_SUCCESS";
export const DELETE_TERMSCONDITION_FAIL = "DELETE_TERMSCONDITION_FAIL";

export const GETALL_TERMSCONDITION_REQUEST = "GETALL_TERMSCONDITION_REQUEST";
export const GETALL_TERMSCONDITION_SUCCESS = "GETALL_TERMSCONDITION_SUCCESS";
export const GETALL_TERMSCONDITION_FAIL = "GETALL_TERMSCONDITION_FAIL";

export const GETDETAIL_TERMSCONDITION_REQUEST =
  "GETDETAIL_TERMSCONDITION_REQUEST";
export const GETDETAIL_TERMSCONDITION_SUCCESS =
  "GETDETAIL_TERMSCONDITION_SUCCESS";
export const GETDETAIL_TERMSCONDITION_FAIL = "GETDETAIL_TERMSCONDITION_FAIL";

export const TERMSCONDITION_CHANGE_STATUS_REQUEST =
  "TERMSCONDITION_CHANGE_STATUS_REQUEST";
export const TERMSCONDITION_CHANGE_STATUS_SUCCESS =
  "TERMSCONDITION_CHANGE_STATUS_SUCCESS";
export const TERMSCONDITION_CHANGE_STATUS_FAIL =
  "TERMSCONDITION_CHANGE_STATUS_FAIL";
