// constant files

export const ADD_TESTIMONIAL_REQUEST = "ADD_TESTIMONIAL_REQUEST";
export const ADD_TESTIMONIAL_SUCCESS = "ADD_TESTIMONIAL_SUCCESS";
export const ADD_TESTIMONIAL_FAIL = "ADD_TESTIMONIAL_FAIL";

export const UPDATE_TESTIMONIAL_REQUEST = "UPDATE_TESTIMONIAL_REQUEST";
export const UPDATE_TESTIMONIAL_SUCCESS = "UPDATE_TESTIMONIAL_SUCCESS";
export const UPDATE_TESTIMONIAL_FAIL = "UPDATE_TESTIMONIAL_FAIL";

export const DELETE_TESTIMONIAL_REQUEST = "DELETE_TESTIMONIAL_REQUEST";
export const DELETE_TESTIMONIAL_SUCCESS = "DELETE_TESTIMONIAL_SUCCESS";
export const DELETE_TESTIMONIAL_FAIL = "DELETE_TESTIMONIAL_FAIL";

export const GETALL_TESTIMONIAL_REQUEST = "GETALL_TESTIMONIAL_REQUEST";
export const GETALL_TESTIMONIAL_SUCCESS = "GETALL_TESTIMONIAL_SUCCESS";
export const GETALL_TESTIMONIAL_FAIL = "GETALL_TESTIMONIAL_FAIL";

export const GETDETAIL_TESTIMONIAL_REQUEST = "GETDETAIL_TESTIMONIAL_REQUEST";
export const GETDETAIL_TESTIMONIAL_SUCCESS = "GETDETAIL_TESTIMONIAL_SUCCESS";
export const GETDETAIL_TESTIMONIAL_FAIL = "GETDETAIL_TESTIMONIAL_FAIL";

export const TESTIMONIAL_CHANGE_STATUS_REQUEST = "TESTIMONIAL_CHANGE_STATUS_REQUEST";
export const TESTIMONIAL_CHANGE_STATUS_SUCCESS = "TESTIMONIAL_CHANGE_STATUS_SUCCESS";
export const TESTIMONIAL_CHANGE_STATUS_FAIL = "TESTIMONIAL_CHANGE_STATUS_FAIL";
