// constant files

export const ADD_USER_DETAIL_REQUEST = "ADD_USER_DETAIL_REQUEST";
export const ADD_USER_DETAIL_SUCCESS = "ADD_USER_DETAIL_SUCCESS";
export const ADD_USER_DETAIL_FAIL = "ADD_USER_DETAIL_FAIL";

export const UPDATE_USER_DETAIL_REQUEST = "UPDATE_USER_DETAIL_REQUEST";
export const UPDATE_USER_DETAIL_SUCCESS = "UPDATE_USER_DETAIL_SUCCESS";
export const UPDATE_USER_DETAIL_FAIL = "UPDATE_USER_DETAIL_FAIL";

export const DELETE_USER_DETAIL_REQUEST = "DELETE_USER_DETAIL_REQUEST";
export const DELETE_USER_DETAIL_SUCCESS = "DELETE_USER_DETAIL_SUCCESS";
export const DELETE_USER_DETAIL_FAIL = "DELETE_USER_DETAIL_FAIL";

export const GET_ALL_USER_DETAIL_REQUEST = "GET_ALL_USER_DETAIL_REQUEST";
export const GET_ALL_USER_DETAIL_SUCCESS = "GET_ALL_USER_DETAIL_SUCCESS";
export const GET_ALL_USER_DETAIL_FAIL = "GET_ALL_USER_DETAIL_FAIL";

export const GET_SINGLE_USER_DETAIL_REQUEST = "GET_SINGLE_USER_DETAIL_REQUEST";
export const GET_SINGLE_USER_DETAIL_SUCCESS = "GET_SINGLE_USER_DETAIL_SUCCESS";
export const GET_SINGLE_USER_DETAIL_FAIL = "GET_SINGLE_USER_DETAIL_FAIL";

export const USER_DETAIL_CHANGE_STATUS_REQUEST =
  "USER_DETAIL_CHANGE_STATUS_REQUEST";
export const USER_DETAIL_CHANGE_STATUS_SUCCESS =
  "USER_DETAIL_CHANGE_STATUS_SUCCESS";
export const USER_DETAIL_CHANGE_STATUS_FAIL = "USER_DETAIL_CHANGE_STATUS_FAIL";
