// constant files

export const ADD_USER_ADDRESS_REQUEST = "ADD_USER_ADDRESS_REQUEST";
export const ADD_USER_ADDRESS_SUCCESS = "ADD_USER_ADDRESS_SUCCESS";
export const ADD_USER_ADDRESS_FAIL = "ADD_USER_ADDRESS_FAIL";

export const UPDATE_USER_ADDRESS_REQUEST = "UPDATE_USER_ADDRESS_REQUEST";
export const UPDATE_USER_ADDRESS_SUCCESS = "UPDATE_USER_ADDRESS_SUCCESS";
export const UPDATE_USER_ADDRESS_FAIL = "UPDATE_USER_ADDRESS_FAIL";

export const DELETE_USER_ADDRESS_REQUEST = "DELETE_USER_ADDRESS_REQUEST";
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS";
export const DELETE_USER_ADDRESS_FAIL = "DELETE_USER_ADDRESS_FAIL";

export const GET_ALL_USER_ADDRESS_REQUEST = "GET_ALL_USER_ADDRESS_REQUEST";
export const GET_ALL_USER_ADDRESS_SUCCESS = "GET_ALL_USER_ADDRESS_SUCCESS";
export const GET_ALL_USER_ADDRESS_FAIL = "GET_ALL_USER_ADDRESS_FAIL";

export const GET_SINGLE_USER_ADDRESS_REQUEST = "GET_SINGLE_USER_ADDRESS_REQUEST";
export const GET_SINGLE_USER_ADDRESS_SUCCESS = "GET_SINGLE_USER_ADDRESS_SUCCESS";
export const GET_SINGLE_USER_ADDRESS_FAIL = "GET_SINGLE_USER_ADDRESS_FAIL";

export const USER_ADDRESS_CHANGE_STATUS_REQUEST = "USER_ADDRESS_CHANGE_STATUS_REQUEST";
export const USER_ADDRESS_CHANGE_STATUS_SUCCESS = "USER_ADDRESS_CHANGE_STATUS_SUCCESS";
export const USER_ADDRESS_CHANGE_STATUS_FAIL = "USER_ADDRESS_CHANGE_STATUS_FAIL";
