// constant files

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const GET_SINGLE_USER_REQUEST = "GET_SINGLE_USER_REQUEST";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_FAIL = "GET_SINGLE_USER_FAIL";

export const USER_CHANGE_STATUS_REQUEST = "USER_CHANGE_STATUS_REQUEST";
export const USER_CHANGE_STATUS_SUCCESS = "USER_CHANGE_STATUS_SUCCESS";
export const USER_CHANGE_STATUS_FAIL = "USER_CHANGE_STATUS_FAIL";

export const USER_IS_ADMIN_REQUEST = "USER_IS_ADMIN_REQUEST";
export const USER_IS_ADMIN_SUCCESS = "USER_IS_ADMIN_SUCCESS";
export const USER_IS_ADMIN_FAIL = "USER_IS_ADMIN_FAIL";

export const USER_IS_STAFF_REQUEST = "USER_IS_STAFF_REQUEST";
export const USER_IS_STAFF_SUCCESS = "USER_IS_STAFF_SUCCESS";
export const USER_IS_STAFF_FAIL = "USER_IS_STAFF_FAIL";
